// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: proto/ledger.proto

package ledgerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountCode   string                 `protobuf:"bytes,1,opt,name=account_code,json=accountCode,proto3" json:"account_code,omitempty"`
	DebitAmount   int64                  `protobuf:"varint,2,opt,name=debit_amount,json=debitAmount,proto3" json:"debit_amount,omitempty"`
	CreditAmount  int64                  `protobuf:"varint,3,opt,name=credit_amount,json=creditAmount,proto3" json:"credit_amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetAccountCode() string {
	if x != nil {
		return x.AccountCode
	}
	return ""
}

func (x *Entry) GetDebitAmount() int64 {
	if x != nil {
		return x.DebitAmount
	}
	return 0
}

func (x *Entry) GetCreditAmount() int64 {
	if x != nil {
		return x.CreditAmount
	}
	return 0
}

func (x *Entry) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Entry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      string                 `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntriesRequest) Reset() {
	*x = CreateEntriesRequest{}
	mi := &file_proto_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntriesRequest) ProtoMessage() {}

func (x *CreateEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntriesRequest.ProtoReflect.Descriptor instead.
func (*CreateEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEntriesRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateEntriesRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateEntriesRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *CreateEntriesRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CreateEntriesRequest) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CreateEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntriesResponse) Reset() {
	*x = CreateEntriesResponse{}
	mi := &file_proto_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntriesResponse) ProtoMessage() {}

func (x *CreateEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntriesResponse.ProtoReflect.Descriptor instead.
func (*CreateEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEntriesResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	AccountCode   string                 `protobuf:"bytes,2,opt,name=account_code,json=accountCode,proto3" json:"account_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetBalanceRequest) GetAccountCode() string {
	if x != nil {
		return x.AccountCode
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	AccountCode   string                 `protobuf:"bytes,2,opt,name=account_code,json=accountCode,proto3" json:"account_code,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetBalanceResponse) GetAccountCode() string {
	if x != nil {
		return x.AccountCode
	}
	return ""
}

func (x *GetBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_proto_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ledger.proto\x12\x11paygate.ledger.v1\"\xb0\x01\n" +
	"\x05Entry\x12!\n" +
	"\faccount_code\x18\x01 \x01(\tR\vaccountCode\x12!\n" +
	"\fdebit_amount\x18\x02 \x01(\x03R\vdebitAmount\x12#\n" +
	"\rcredit_amount\x18\x03 \x01(\x03R\fcreditAmount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xd0\x01\n" +
	"\x14CreateEntriesRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x122\n" +
	"\aentries\x18\x05 \x03(\v2\x18.paygate.ledger.v1.EntryR\aentries\">\n" +
	"\x15CreateEntriesResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"W\n" +
	"\x11GetBalanceRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12!\n" +
	"\faccount_code\x18\x02 \x01(\tR\vaccountCode\"r\n" +
	"\x12GetBalanceResponse\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12!\n" +
	"\faccount_code\x18\x02 \x01(\tR\vaccountCode\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance2\xce\x01\n" +
	"\rLedgerService\x12b\n" +
	"\rCreateEntries\x12'.paygate.ledger.v1.CreateEntriesRequest\x1a(.paygate.ledger.v1.CreateEntriesResponse\x12Y\n" +
	"\n" +
	"GetBalance\x12$.paygate.ledger.v1.GetBalanceRequest\x1a%.paygate.ledger.v1.GetBalanceResponseB;Z9github.com/sanskarpan/PayGate/internal/ledger/pb;ledgerpbb\x06proto3"

var (
	file_proto_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_proto_rawDescData []byte
)

func file_proto_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_proto_rawDescData
}

var file_proto_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_ledger_proto_goTypes = []any{
	(*Entry)(nil),                 // 0: paygate.ledger.v1.Entry
	(*CreateEntriesRequest)(nil),  // 1: paygate.ledger.v1.CreateEntriesRequest
	(*CreateEntriesResponse)(nil), // 2: paygate.ledger.v1.CreateEntriesResponse
	(*GetBalanceRequest)(nil),     // 3: paygate.ledger.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 4: paygate.ledger.v1.GetBalanceResponse
}
var file_proto_ledger_proto_depIdxs = []int32{
	0, // 0: paygate.ledger.v1.CreateEntriesRequest.entries:type_name -> paygate.ledger.v1.Entry
	1, // 1: paygate.ledger.v1.LedgerService.CreateEntries:input_type -> paygate.ledger.v1.CreateEntriesRequest
	3, // 2: paygate.ledger.v1.LedgerService.GetBalance:input_type -> paygate.ledger.v1.GetBalanceRequest
	2, // 3: paygate.ledger.v1.LedgerService.CreateEntries:output_type -> paygate.ledger.v1.CreateEntriesResponse
	4, // 4: paygate.ledger.v1.LedgerService.GetBalance:output_type -> paygate.ledger.v1.GetBalanceResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ledger_proto_init() }
func file_proto_ledger_proto_init() {
	if File_proto_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_proto_depIdxs,
		MessageInfos:      file_proto_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_proto = out.File
	file_proto_ledger_proto_goTypes = nil
	file_proto_ledger_proto_depIdxs = nil
}
